#!/bin/bash

. "$MUNIN_LIBDIR/plugins/plugin.sh"

if [ "$1" = "autoconf" ]; then
  echo yes
  exit 0
fi

if [ "$1" = "config" ]; then

  echo 'graph_title Room CO2 concentration'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_vlabel ppm'
  echo 'graph_info Room CO2 concentration'

  echo 'graph_scale no'
  echo 'graph_category sensors'

  echo 'co2mini.label CO2-mini'
  echo 'co2mini.info CO2-mini'

  # Last, if run with the "config"-parameter, quit here (don't
  # display any data)
  exit 0
fi

echo -n "co2mini.value "
co2-mini | cut -d' ' -f1
